### PR TITLE
fixed invalid uuids, added test

### PR DESCRIPTION
**Pull request by ArtskydJ**
The uuids used to be generated incorrectly. The 'y' value was between 8 and F, when it should be between 8 and B.

https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_.28random.29

See [jsfiddle](https://jsfiddle.net/8o4t5wqz/).

### CODE REVIEW

**Comment by TehShrike** [comment]
I suppose [assert](https://www.npmjs.com/package/assert) should be added to the `devDependencies`

**Comment by ArtskydJ** [comment]
[assert](https://nodejs.org/api/assert.html) is built into the node core.

**Comment by TehShrike** [comment]
oh right duh!

**Comment by leahciMic** [comment]
Thanks for the PR @ArtskydJ . LGTM!

**Pull request merged**
